repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: end-of-file-fixer
  - id: mixed-line-ending
